### ISSUE TITLE
youtube upload problem

### ISSUE THREAD

**Issue by punktire** [google/spatial-media#128]
Hello!

recently im trying to learn and make some contents with ambisonic.
so i trying to make some of test clips and upload it to youtube.

first time i follow google help to make clip then use metadata injector app to tagging. i check spherical , spatial audio.
(https://support.google.com/jump/answer/6399978?hl=en&ref_topic=6399805)
video works well on youtube but spatial audio did not work with 3D navigation.

then i trying to python script to tagging. but its not work for me too.
another approach was each video and audio combine by ffmpeg. and its same as before...
(ffmpeg -i myfile.mov -i YouTube_spatial_audio.wav -map 0:v -map 1:a -channel_layout 4.0 -c copy -shortest ffmpeg_test_4.mov)

What should i do for now?

Thanks!

**Comment by dcower** [comment]
Hi @punktire,

Just to verify -- after checking the boxes, did you select **Inject metadata**, save a new file, and then upload _that_ file? See these instructions: https://support.google.com/jump/answer/7044297?hl=en&ref_topic=6399805

Dillon

**Comment by punktire** [comment]
Hi!

Yes save file with meta injector. and even trying to do that in terminal with python.
After saving file i open it on hex editor then I found SA3D at metadata section.

I can't figure out what was wrong with my process;;

Thanks!

**Comment by punktire** [comment]
I'd send file and youtube link to you. Thanks!

**Comment by punktire** [comment]
Hi again~ did u get the file and youtube link? Still i didn't find way to upload correctly...
Waiting for reply~
Thank you!

**Comment by invitriol** [comment]
hi, i have the same problem! and yes i injected metadata and waited several hours, i finally even used an outplay from googles reaper example. is there a bug at the moment? as punktire i uploaded all pos. combinations in ffmpeg too... youtube is just playing a stereo file. no panning/reaction. thnx

**Comment by shanevan** [comment]
Hi guys, I am also having issues uploading my videos with spatial audio at the moment. Pretty much the same as above, I have had success with a few tests working really well but since last Friday I have not had any luck with the upload process to YouTube. 

The only difference between my earlier tests and more recent tests is that I was originally using a 15 second video and now I am working with a 1:15 video. Same number of channels and process! 

Is it something on the YouTube side thats not happening when we upload? Im struggling to think what the difference is..

Also, I would love to know what the rough encoding time is for spatial audio once it has been uploaded to YouTube...15 seconds seems to take around 1 hour to be able to hear the effects. Is it different for different length videos? 

Any info on the above issues would be greatly appreciated! 
Cheers

**Comment by punktire** [comment]
First time im trying all the process with osx, and today im trying to do this with windows...
but nothing changes... (all metadata injected by meta injector v2)

**Comment by punktire** [comment]
Now all video that i upload work spatial audio well even uploaded before.
How about yours invitriol?
I guess some paring problem in youtube player had solved now.
Thanks for support!
