### ISSUE TITLE
Norton Blocking Spatial Metadata Injector Tool as Malware

### ISSUE THREAD

**Issue by maxheadspace** [google/spatial-media#130]
Symantec Norton security software will not let me install the YouTube Spatial Metadata Injector Tool on my Windows 10 computer.  As soon as I unzip it onto my desktop, Norton immediately removes it explaining that it is a trojan malware.  It will not even let me override the removal.  I can't find anything on line even referencing this.  I even did searches on the Symantec web site, but nothing.  So am I the only person who is being "protected" in this manner?

**Comment by pwroberts** [comment]
Hi @maxheadspace,

Thanks for reporting this. We saw some false positives from certain antivirus software back in June (see https://github.com/google/spatial-media/issues/97 for details), and we updated the Windows metadata injector download to use a 64-bit binary instead of a 32-bit binary, which stopped the false positives. Can you make sure you have the latest Windows ZIP file from https://github.com/google/spatial-media/releases/latest?

If your antivirus is still preventing you from running the metadata injector, you can run it directly from the Python source code:

* Install Python 2 from https://www.python.org/
* Download and extract the metadata injector source code from https://github.com/google/spatial-media/archive/v2.0.zip
* From the "spatialmedia" directory inside the extracted archive, run "gui.py" (double click it in Windows Explorer or run "python gui.py" from the Windows command prompt).

Thanks,

Paul
