### ISSUE TITLE
Error: Leaf Box Exceeds Bounds

### ISSUE THREAD

**Issue by rarroyo29** [google/spatial-media#133]
Is there a solution or workaround for this error?  The video failed to load.

**Comment by SahilMadan** [comment]
Hey rarroyo29,

I think first verify that the file you're using is a valid mp4 file. It might just be an issue there. Otherwise, if you're still having issues and you're happy to share, we're happy to take a look. You can upload to Google Drive and private message me the link on Github. Alternatively, feel free to email me a link to the file at sahilmadan  at   google   dot  com.

**Comment by pwroberts** [comment]
Hi @rarroyo29,

Are you still running into this problem? As Sahil said last week, we'd be happy to take a look at your video and see if we can see what's wrong.

**Comment by pulquero** [comment]
I have a similar problem. Link emailed to you.

**Comment by pulquero** [comment]
I've identified the problem in my case. I was using H264 format for my MP4 instead of MPEG-4 format with H264 encoding. I guess the solution to this issue would be to have a more helpful/informative error message.

**Comment by clockzhong** [comment]
> I've identified the problem in my case. I was using H264 format for my MP4 instead of MPEG-4 format with H264 encoding. I guess the solution to this issue would be to have a more helpful/informative error message.

pulquero, then how can we fix it? There is no any place for use to specify the codecs type in this command: "python spatialmedia", right? How you fixed your problem?

**Comment by shitchell** [comment]
> How you fixed your problem?

I'm not pulquero, but for anyone else who stumbles upon this, I fixed it by using `ffmpeg` to convert the encoding format:

```sh
ffmpeg -i original_video.mp4 -vcodec libx264 -acodec aac spatialmedia_compatible.mp4
```
