### ISSUE TITLE
Leaf box size exceeds bounds

### ISSUE THREAD

**Issue by Sn4ke66** [google/spatial-media#140]
How can I fix this error or what does it mean??
Help pls

**Comment by SahilMadan** [comment]
I think first verify that the file you're using is a valid mp4 file -- it could be a problem with the mp4 file header having incorrect information about the rest of the file (essentially saying the leaf box size is a certain value when it isn't). Otherwise, if you're still having issues and you're happy to share, we're happy to take a look at the file. You can upload to Google Drive and private message me the link on Github. Alternatively, feel free to email me a link to the file at sahilmadan at google dot com.

**Comment by acolwell** [comment]
Closing since this appears to be a duplicate of #133
