### ISSUE TITLE
Add native webm / mkv support (individual parsing).

### ISSUE THREAD

**Issue by suderman-google** [google/spatial-media#17]

**Comment by nuclearsugar** [comment]
I'm running into some major hurdles in trying to get 8k UHD spherical media onto youtube. I've managed to render to the WebM format ([plugin](http://www.fnordware.com/WebM/)), but getting the spherical media tag injected is proving to be very difficult.

MP4's max resolution is 3840 × 2160. I'm not sure if Apple Pro Res 422 HQ can render to 8k. So I'm stuck using WebM since it's the only 8k format Youtube accepts.

I see in other discussions that there are currently some platform issues with supporting WebM. But is there a way to inject the spherical media tag manually?

**Comment by dcower** [comment]
Hey @nuclearsugar, we don't have support for MKV/WebM currently, but I believe I do have a solution for you!

The metadata injector supports MOV containers, which 8k video is supported in, so you should be able to transcode (e.g., using [FFmpeg](https://ffmpeg.org)) to ProRes or H.264 in a MOV container and then use the injector on that. [This page](https://trac.ffmpeg.org/wiki/Encode/VFX) has more information on using FFmpeg to encode using ProRes.

Let me know if you still have any issues; I'm happy to help out.

**Comment by nuclearsugar** [comment]
Thank you @dcower! Your technique worked perfectly. I converted the WebM to a MOV (ProRes) in FFmpeg. Cheers.

**Comment by dcower** [comment]
No problem! Glad I could help. :)

**Comment by tlk8000** [comment]
But when you convert your 8K webm to a mov, do you still retain the efficient file size, and quality?

**Comment by wonson** [comment]
mshp is not supported in ffmpeg
