### ISSUE TITLE
4:20 limitation bug

### ISSUE THREAD

**Issue by xNaXx** [google/spatial-media#185]
I've got a .mp4 h264 which lasts 5:39.

After injecting 360 metadata to my video with the tool, seems to last the same... BUT when I upload it to YouTube or even Vimeo, they both last 4:20.

I assume that's a bug, which automatically injects some kind of duration metadata value into the video.

**Comment by xNaXx** [comment]
Btw, I actually uploaded the video with any injection to Vimeo, and checked the 360 checkbox, and everything is fine.
The problem is I can't do that in Youtube. It does not recognize the 360 video, unless I inject it the metadata.

**Comment by kimomoki** [comment]
Thank you for contacting me, sorry for not answering your question. I use
the google tool to insert metadata into the 360 video but seems it not fit
for my camera, there is a big gap in my 360 video.
 You should check aframe, I can not access because of network problems.

2017-12-13 6:51 GMT+08:00 xNaXx <notifications@github.com>:
