### ISSUE TITLE
Mac version appears to be broken

### ISSUE THREAD

**Issue by gondolio** [google/spatial-media#211]
Running Mac OS 10.14.1, and 8.5.9 of Tcl & Tk, and per attached screenshots things don't appear to be functioning - the UI is blurred and can't tick any boxes etc:

![image](https://user-images.githubusercontent.com/4338344/50066938-d39cc400-0201-11e9-8646-64035f9a1f2b.png)

**Comment by mgorzel** [comment]
Thanks for reporting @gondolio! There seems to be a problem with Tkinter after upgrading to Mojave (see, for example [here](https://stackoverflow.com/questions/52529403/button-text-of-tkinter-not-works-in-mojave)). The text in the buttons is not being displayed, but the buttons should still be clickable (the checkboxes are only clickable after you select a video). As a temporary workaround, you could slighlty re-size the GUI and the text on the buttons should reappear.

It should be fixed in the next release. Thanks!

**Comment by gondolio** [comment]
Thank you for the quick reply and suggestion Marcin!

**Comment by tdlivings** [comment]
Thank you for making this app 64 bit.
