### ISSUE TITLE
Showing "Failed to load file" error

### ISSUE THREAD

**Issue by karthhic** [google/spatial-media#217]
When i tried to open a stitched video file it is showing failed to load file error.

**Comment by delpiero224** [comment]
Same for me. Tried to import a Gear 360 video (already converted with opening it in ActionDirector once), but getting the error message.

If I would like to edit the raw footage it would work, but looks ugly.

**Comment by antoniobejar** [comment]
Same for me

**Comment by polaris911** [comment]
Getting the same error for Gear 360 (2016) video converted with ActionDirector

**Comment by nauseum** [comment]
Same issue. Failed to load file.

**Comment by alexeeve801** [comment]
I tried to import a stitch video file but I get "Failed to load file xxxxx.mp4" error.  Please help.

**Comment by wrecche** [comment]
> 
> 
> When i tried to open a stitched video file it is showing failed to load file error.

I am getting the same. However, I think it is due to how Action Director encodes the file. I used FreeMake Video Converter to convert it back into an MP4 file, and it then allowed me to inject the exif data, and I was then able to upload it to youtube to test it was actually a 360 object, which it was. Good thing about freemake is that it's relatively easy to bulk convert files. ffmpeg could probably do the same.

So, a simple conversion, just another laborious step in getting things off the gear 360 and into a usable format. It should not be so hard for a company like Samsung to produce usable software..

**Comment by sverit** [comment]
Same here, stitched with ActionDirector.
