### ISSUE TITLE
Black holes created at top and bottom after metadata injection

### ISSUE THREAD

**Issue by cponce-uncc** [google/spatial-media#229]
After injecting the video with the metadata and uploading the video to YouTube, I noticed that two black holes (one on the bottom and one on the top) appeared. I am unsure if this is a problem with the editor (DaVinci Resolve 16) or the metadata injection. I attempted to fix this by adjusting the resolution to 1960x960, but this resulted in both the circles as well as a horizontal black bar. Is this an issue on the side of injection or the editing and exporting? 

Thanks!

**Comment by internet007** [comment]
me too :(

**Comment by AlexSenties** [comment]
I suffered the same thing, but I used iMovie, so it can't be the editor because I doubt two different ones suffer the same bug. Plus, the panoramic image before the injection does not have black at the top and bottom, so I suspect it is the injector. What injector did you use? I used this one: _Spatial Media Metadata Injector_
<img width="616" alt="Screen Shot 2020-12-13 at 8 44 59 PM" src="https://user-images.githubusercontent.com/62629188/102034611-127b9b00-3d84-11eb-895b-69f7e173ea3a.png">

**Comment by JDiPierro** [comment]
I'm having this issue as well. I'm using a GoPro Max and I don't get the holes in the GoPro players. I'm export mp4s, editing in Hitfilm Express, then using the metadata injector on the final export. I can open the video in VLC and see the black holes there so it doesn't appear to be just a Youtube problem. The area around the black holes looks warped because the footage is there, but the players refuse to close the black hole for some reason..

I'm using Spatial Media Metadata Injector v2.1

**Comment by diclebozdereli** [comment]
I had the same problem. But here is how I fixed it:
Even if there was no black holes on my renders, I was seeing them on top and the bottom of my video. In my case, the problem wasn’t the render engine or the injector, it was my media encoder settings. I am using After Effects and rendering it in AME to get my mp4. When the preset is on ‘Match source-highbitrate’ there is no black hole on the output. (My source resolution was 2160x1080). But, when I try to set my preset on one of the Ultra HD or 4K Resolutions, both of them appeared with black circle after injection. So I think the solution is exporting the mp4 with the resolution that matches with the source since the other resolution types do not have 2:1 ratio that is required for 360 videos.

**Comment by skillmatic-co** [comment]
I'm having the same issue.
