### ISSUE TITLE
Workflow Question

### ISSUE THREAD

**Issue by DrWig** [google/spatial-media#75]
Hi.  I'm looking into adding Ambisonic Audio to video files, but I'm not quite clear of the workflow/tools.

Jump Inspector help suggests making an MKV from a MP4/MOV/MKV video with an Ambisonic Wave file added.

Spatial media tools (to add required meta data) only works on MP4 files (and not Wave or MKV files).

So, if I have an audio free .MOV video and 4-channel wave file containing Ambix Audio, what do I have to do to get them working correctly other than using FFMPEG to glue them together as per the Jump inspector help file.

Do I have to tag both the video and audio files BEFORE FFMPEGing them?  Or do I really need to FFMPEG them to an MP4 and then use the spatial-media tools to give them the correct meta-data?

We've got plenty of videos with Ambisonic audio (up to 4th order) and it'd be great to be able to present them in this way.
#
cheers

Bruce

**Comment by DrWig** [comment]
FFMPEGing to AAC and MP4, then tagging with the spatial-media tools, and then using jump inspector results in the same.  The AmbiX to binaural conversion/decoding seems to be not working as well as it should.

I think I'm missing something here......

**Comment by dcower** [comment]
Hi @DrWig, I believe you've since [http://www.brucewiggins.co.uk/?p=666#content](figured most of this out) :), but for any future confused readers, Bruce's aforementioned article is a great guide.

We've also added [Jump Help](http://g.co/jump/help) articles for [spatial audio](https://support.google.com/jump/answer/6399746?hl=en&ref_topic=6399824), [ambisonic audio production in REAPER](https://support.google.com/jump/answer/6399978?hl=en&ref_topic=6399805), and more.

In addition, [Jump Inspector](http://g.co/jump/inspector) now supports uncompressed 16-bit PCM audio in .mov files, which you can _also_ inject with spatial media metadata and upload to YouTube; so we're no longer suggesting MKV/Vorbis as a preview container/format.
