### ISSUE TITLE
Documentation for running CLI metadata injector is confusing

### ISSUE THREAD

**Issue by bquandt** [google/spatial-media#86]
The build docs are not in sync with the code.  Trying to figure out how to make the cli version of this tool to report tags inserted into a previously processed file, can't seem to figure out how to make the tool do that.

**Comment by dcower** [comment]
Hi @bquandt, what issue are you running into specifically?

**Comment by bquandt** [comment]
Build instructions on github, executable/script file name are not in sync
with the actual code.

In short the github build instuctions really are more misleading then much
more.

**Comment by dcower** [comment]
I think the issue you might be running into is that you're running the script from the directory containing `__main__.py`, rather than the directory _above_ it; i.e., `python spatialmedia` should be run from the directory containing the directory `spatialmedia`. We have a small blurb about it, but I agree that it's confusing as is.

Thanks for bringing up the issue. I'll take a look at what we can do to simplify the documentation.

**Comment by dcoffey3296** [comment]
Agree on confusing but this thread is very helpful thanks!
