### ISSUE TITLE
problem with metadata injector,  spherical checkbox missing ? 

### ISSUE THREAD

**Issue by 3drille** [google/spatial-media#93]
hi i have a problem with metadata injector, 

missing checkboxes in app   spherical checkbox ? 
have downloaded the app from: 
https://github.com/google/spatial-media/releases/download/v2.0/360.Video.Metadata.Tool.win.zip

It looks wrong like its missing some stuff in the app ??

please help :-)
I would like to post a 360-video on youtube..

![error](https://cloud.githubusercontent.com/assets/19834563/15924591/2e334e34-2e33-11e6-9d64-238b63d0c32d.jpg)

**Comment by suderman-google** [comment]
Hey 3drille,

The app has actually been updated so there is no more spherical button but it still injects the metadata. Just open your file, then click checkboxes if the video is stereo (in a top/bottom layout) or if it has spherical audio. After, click "Inject Metadata" and you should be done.

We are still in the process of updating the docs so if you could refer to where you read about the spherical checkbox, please post a link to the bug and we will get it updated ASAP.

**Comment by 3drille** [comment]
thanks for the reply :-)
works fine now :-)


documentation on the google/YouTube help page 360 video
https://support.google.com/youtube/answer/6178631?hl

Create a 360-enabled file with an app
Download the 360 Video Metadata app for Mac or Windows.
Un-zip the file, then open the 360 Video Metadata app. If you're on a Mac, you may need to right-click the app and then click Open.
Select the video file.
Select the checkbox for Spherical and click Save as. Do not select the "3D Top-bottom" checkbox. For more information, refer to upload instructions for virtual reality videos.
Enter a name for the file that will be created.
Save the file. A new file will be created automatically in the same location as the original file.
Upload the new file to YouTube.
Wait for the 360° effect to process. This may take up to an hour.
You can also add the metadata using a Python script.

**Comment by yanbs1** [comment]
How did you resolve this problem? the metadata injector i have also do not have a spherical checkbox

**Comment by Carlossal** [comment]
Like Yanbs1 above, I have attempted to use the tool, so I've clicked open, then checking no boxes (unsuitable for my camera, theta s) I'm clicking inject metadata. My interpretation of suderman-google's reply is that that should work? YouTube really doesn't like the videos, and when played on a 360 video app, they're 90 degrees out. I'm confused!

**Comment by suderman-google** [comment]
Hey yanbs1 and Carlossal,

Carlossal is correct. Opening the file then clicking inject metadata should be sufficient, the application was updated so that it no longer required a "spherical" checkbox (we assume a user desires to mark the video as spherical).

Carlossal: Could you clarify what you mean by the video is 90 degrees out? Do you mean it is rotated from how you would prefer?

**Comment by Carlossal** [comment]
Howdy, absolutely, in order to view the video the phone (and user's head, if using cardboard, say) has to be in portrait rather than landscape. YouTube doesn't interpret it as a stereo video either. There's a reasonable chance it is me, but this seemed a sensible place to start after attempting a few other things to remedy my issues!
